#---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-- Data for m_currency
#---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Lek', 'ALL', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Algerian Dinar', 'DZD', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Argentine Peso', 'ARS', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Australian Dollar', 'AUD', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Bahamian Dollar', 'BSD', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Bahraini Dinar', 'BHD', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Taka', 'BDT', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Armenian Dram', 'AMD', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Barbados Dollar', 'BBD', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Bermudian Dollar', 'BMD', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Ngultrum', 'BTN', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Boliviano', 'BOB', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Pula', 'BWP', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Belize Dollar', 'BZD', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Solomon Islands Dollar', 'SBD', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Brunei Dollar', 'BND', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Kyat', 'MMK', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Burundi Franc', 'BIF', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Riel', 'KHR', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Canadian Dollar', 'CAD', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Cabo Verde Escudo', 'CVE', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Cayman Islands Dollar', 'KYD', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Sri Lanka Rupee', 'LKR', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Chilean Peso', 'CLP', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Yuan Renminbi', 'CNY', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Colombian Peso', 'COP', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Comoro Franc', 'KMF', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Costa Rican Colon', 'CRC', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Kuna', 'HRK', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Cuban Peso', 'CUP', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Czech Koruna', 'CZK', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Danish Krone', 'DKK', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Dominican Peso', 'DOP', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('El Salvador Colon', 'SVC', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Ethiopian Birr', 'ETB', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Nakfa', 'ERN', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Falkland Islands Pound', 'FKP', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Fiji Dollar', 'FJD', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Djibouti Franc', 'DJF', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Dalasi', 'GMD', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Gibraltar Pound', 'GIP', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Quetzal', 'GTQ', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Guinea Franc', 'GNF', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Guyana Dollar', 'GYD', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Gourde', 'HTG', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Lempira', 'HNL', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Hong Kong Dollar', 'HKD', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Forint', 'HUF', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Iceland Krona', 'ISK', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Indian Rupee', 'INR', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Rupiah', 'IDR', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Iranian Rial', 'IRR', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Iraqi Dinar', 'IQD', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('New Israeli Sheqel', 'ILS', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Jamaican Dollar', 'JMD', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Yen', 'JPY', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Tenge', 'KZT', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Jordanian Dinar', 'JOD', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Kenyan Shilling', 'KES', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('North Korean Won', 'KPW', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Won', 'KRW', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Kuwaiti Dinar', 'KWD', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Som', 'KGS', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Kip', 'LAK', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Lebanese Pound', 'LBP', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Loti', 'LSL', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Liberian Dollar', 'LRD', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Libyan Dinar', 'LYD', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Pataca', 'MOP', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Kwacha', 'MWK', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Malaysian Ringgit', 'MYR', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Rufiyaa', 'MVR', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Ouguiya', 'MRO', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Mauritius Rupee', 'MUR', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Mexican Peso', 'MXN', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Tugrik', 'MNT', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Moldovan Leu', 'MDL', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Moroccan Dirham', 'MAD', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Rial Omani', 'OMR', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Namibia Dollar', 'NAD', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Nepalese Rupee', 'NPR', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Netherlands Antillean Guilder', 'ANG', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Aruban Florin', 'AWG', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Vatu', 'VUV', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Cordoba Oro', 'NIO', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Naira', 'NGN', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Norwegian Krone', 'NOK', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Pakistan Rupee', 'PKR', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Balboa', 'PAB', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Kina', 'PGK', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Guarani', 'PYG', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Nuevo Sol', 'PEN', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Philippine Peso', 'PHP', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Qatari Rial', 'QAR', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Russian Ruble', 'RUB', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Rwanda Franc', 'RWF', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Saint Helena Pound', 'SHP', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Dobra', 'STD', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Saudi Riyal', 'SAR', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Seychelles Rupee', 'SCR', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Leone', 'SLL', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Singapore Dollar', 'SGD', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Dong', 'VND', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Somali Shilling', 'SOS', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Rand', 'ZAR', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('South Sudanese Pound', 'SSP', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Lilangeni', 'SZL', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Swedish Krona', 'SEK', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Swiss Franc', 'CHF', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Syrian Pound', 'SYP', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Baht', 'THB', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Pa’anga', 'TOP', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Trinidad and Tobago Dollar', 'TTD', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('UAE Dirham', 'AED', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Tunisian Dinar', 'TND', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Uganda Shilling', 'UGX', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Denar', 'MKD', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Egyptian Pound', 'EGP', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Pound Sterling', 'GBP', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Tanzanian Shilling', 'TZS', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('US Dollar', 'USD', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Peso Uruguayo', 'UYU', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Uzbekistan Sum', 'UZS', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Tala', 'WST', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Yemeni Rial', 'YER', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('New Taiwan Dollar', 'TWD', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Peso Convertible', 'CUC', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Zimbabwe Dollar', 'ZWL', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Turkmenistan New Manat', 'TMT', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Ghana Cedi', 'GHS', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Bolivar', 'VEF', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Sudanese Pound', 'SDG', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Serbian Dinar', 'RSD', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Mozambique Metical', 'MZN', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Azerbaijanian Manat', 'AZN', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Romanian Leu', 'RON', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('WIR Euro', 'CHE', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('WIR Franc', 'CHW', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Turkish Lira', 'TRY', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('CFA Franc BEAC', 'XAF', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('East Caribbean Dollar', 'XCD', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('CFA Franc BCEAO', 'XOF', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('CFP Franc', 'XPF', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('SDR (Special Drawing Right)', 'XDR', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('ADB Unit of Account', 'XUA', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Zambian Kwacha', 'ZMW', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Surinam Dollar', 'SRD', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Malagasy Ariary', 'MGA', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Unidad de Valor Real', 'COU', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Afghani', 'AFN', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Somoni', 'TJS', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Kwanza', 'AOA', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Belarussian Ruble', 'BYR', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Bulgarian Lev', 'BGN', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Congolese Franc', 'CDF', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Convertible Mark', 'BAM', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Euro', 'EUR', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Mexican Unidad de Inversion (UDI)', 'MXV', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Hryvnia', 'UAH', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Lari', 'GEL', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Mvdol', 'BOV', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Zloty', 'PLN', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Brazilian Real', 'BRL', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Unidad de Fomento', 'CLF', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('Sucre', 'XSU', 'Active', now(), 'Mahaboob Subahan');
INSERT INTO `ninoxerp`.`m_currency` (`ccy_name`, `ccy_code`, `ccy_status`, `last_updated_date`, `last_updated_by`) VALUES ('US Dollar (Next day)', 'USN', 'Active', now(), 'Mahaboob Subahan');
